// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJatBPjVvpqKQyN_nV2SZ0lzN4nnwYVXY',
    appId: '1:852927028569:web:2449818d6c6c045c680048',
    messagingSenderId: '852927028569',
    projectId: 'jimbuddy-9e83f',
    authDomain: 'jimbuddy-9e83f.firebaseapp.com',
    databaseURL:
        'https://jimbuddy-9e83f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jimbuddy-9e83f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmCEU-ZGdcf0plMgZ-XrSm9WYi6HwHD8I',
    appId: '1:852927028569:android:5207913ec2e47a86680048',
    messagingSenderId: '852927028569',
    projectId: 'jimbuddy-9e83f',
    databaseURL:
        'https://jimbuddy-9e83f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jimbuddy-9e83f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJvqeeYkjE3oCHRx8KR7xJ0VekD63MaMA',
    appId: '1:852927028569:ios:71b0e38930d30f28680048',
    messagingSenderId: '852927028569',
    projectId: 'jimbuddy-9e83f',
    databaseURL:
        'https://jimbuddy-9e83f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jimbuddy-9e83f.appspot.com',
    iosClientId:
        '852927028569-gvhf82goedjgq3vofc54tjovhhrcmktt.apps.googleusercontent.com',
    iosBundleId: 'com.example.jimBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJvqeeYkjE3oCHRx8KR7xJ0VekD63MaMA',
    appId: '1:852927028569:ios:71b0e38930d30f28680048',
    messagingSenderId: '852927028569',
    projectId: 'jimbuddy-9e83f',
    databaseURL:
        'https://jimbuddy-9e83f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jimbuddy-9e83f.appspot.com',
    iosClientId:
        '852927028569-gvhf82goedjgq3vofc54tjovhhrcmktt.apps.googleusercontent.com',
    iosBundleId: 'com.example.jimBuddy',
  );
}
